### ISSUE TITLE
Uploading HOBO data from Pepperwood

### ISSUE THREAD

**Issue by CelesteDodge** [dackerly/PepperwoodVegPlots#2]
Hi Meagan and David,

I am new to GitHub and have an updated Master.db with all of the HOBO data for vegplots that I would like to share. Can we enable that?

**Comment by MeaganOldfather** [comment]
Hi Celeste, 

Go to the HOBO folder in this repository. Click "create new file". This will fork the PepperwoodVegPlot repository, making a copy that you can make a suggested change to the folder (i.e. upload a file).  Once you have uploaded the correct new file, create a new branch (this will be an option above the commit button) and  start a pull request. Please add descriptions for the commit.

**Comment by CelesteDodge** [comment]
Thanks for the tips Meagan. That is a little confusing! I tried to upload the new master file, but it is about 4x too big. I was able to put it on box for you though. What would you like me to put onto GitHub for you guys?

**Comment by MeaganOldfather** [comment]
The file may be too big because it is a .db, but it may be too large as .csv too. It may be workable to upload the data as one folder per plot, like how the data is organized now. Lets discuss further what needs to be put up on GitHub during the meeting on Thursday.

**Comment by CelesteDodge** [comment]
Sounds good thanks!

Best,

Celeste Dodge, MS
Systems Ecologist
Pepperwood Preserve
2130 Pepperwood Preserve Road
Santa Rosa, CA 95404-7543

Phone: (707) 591-9310 x 207
